# Generated by Django 3.1 on 2020-08-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_auto_20200814_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='s_logo',
            field=models.CharField(max_length=50),
        ),
    ]
